spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tp_music?useSSL=false&serverTimezone=UTC
      username: root
      password: lhg5665655+
  redis:
    host: 192.168.41.100
    port: 6379
    password: lhg5665655+
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#
logging:
  config: classpath:logback.xml


#  devtools:
#    restart:
#      enabled: true
#      additional-paths: E:\JavaProject\myProject\music\clint\src\main\java
#

server:
  port: 8888

